
name: spm

services:

  app:
    build: .
    restart: no
    depends_on:
      mongo:
        condition: service_started
    networks:
      default:
      main_net:
        ipv4_address: $APP_IP
    ports:
      - $HTTP_PORT:8080
    environment:
      - DB_APP_USER=$DB_APP_USER
      - DB_APP_PASS=$DB_APP_PASS
      - APP_IP=$APP_IP
      - DB_IP=$DB_IP
      - HTTP_PORT=$HTTP_PORT
      - DB_PORT=$DB_PORT
      - NODE_ENV=$NODE_ENV

  mongo:
    image: mongo:latest
    restart: no
    networks:
      default:
      main_net:
        ipv4_address: $DB_IP
    ports:
      - $DB_PORT:27017
    volumes:
      - db_data:/data/db:rw
    configs:
      - source: mongo_setup
        target: /mongo-setup.js
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_ROOT_USER
      - MONGO_INITDB_ROOT_PASSWORD=$DB_ROOT_PASS
      - DB_ROOT_USER=$DB_ROOT_USER
      - DB_ROOT_PASS=$DB_ROOT_PASS
      - DB_APP_USER=$DB_APP_USER
      - DB_APP_PASS=$DB_APP_PASS
      - DB_IP=$DB_IP
      - DB_PORT=$DB_PORT

volumes:
  db_data:

configs:
  mongo_setup:
    file: ./mongo-setup.js

networks:

  main_net:
    driver: bridge
    attachable: false
    ipam:
      driver: default
      config:
        - subnet: 192.168.5.0/24
          ip_range: 192.168.5.0/24
          gateway: 192.168.5.1
    